### ISSUE TITLE
level 33 failed...looks like a bug???

### ISSUE THREAD

**Issue by EverLin33** [Gazler/githug#199] opened 2016-01-07 02:46 UTC
using cmd on Windows7...
and I tried to modify the githug-0.4.5\levels\checkout_tag.rb file to get it passed, failed again...

D:\Downloads\githug-data\git_hug>githug reset
********************************************************************************

*                                    Githug                                    *

********************************************************************************

resetting level

Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.

D:\Downloads\githug-data\git_hug>git checkout v1.2
Note: checking out 'v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d7a053c... Some more changes

D:\Downloads\githug-data\git_hug>githug play
********************************************************************************

*                                    Githug                                    *

********************************************************************************

Sorry, this solution is not quite right!
Don't forget you can type `githug hint` for a hint and `githug reset` to reset t
he current level.

Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.

**Comment by Gazler** [comment] 2016-01-07 08:37
I am not getting this error. Could you please download this file https://gist.github.com/Gazler/2e5410fd06d814a92516 (to anywhere except the git_hug directory) and run:

```
githug reset PATH_TO_FILE
git checkout v1.2
githug test PATH_TO_FILE --errors
```

Then paste the output?

**Comment by EverLin33** [comment] 2016-01-08 01:37
Here is the output:

D:\Downloads\githug-data\git_hug>githug reset PATH_TO_FILE
********************************************************************************

*                                    Githug                                    *

********************************************************************************

Level does not exist

D:\Downloads\githug-data\git_hug>git checkout v1.2
Note: checking out 'v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 855176a... Some more changes

D:\Downloads\githug-data\git_hug>githug test PATH_TO_FILE --errors
********************************************************************************

*                                    Githug                                    *

********************************************************************************

C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/lib/githug/game.rb
:38:in `test_level': undefined method `full_description' for false:FalseClass (N
oMethodError)
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/lib/g
ithug/cli.rb:24:in `test'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or/task.rb:22:in `run'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or/invocation.rb:118:in `invoke_task'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or.rb:263:in `dispatch'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or/base.rb:389:in `start'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/bin/g
ithug:4:in `<top (required)>'
        from C:/Program Files/Ruby21/bin/githug:23:in `load'
        from C:/Program Files/Ruby21/bin/githug:23:in `<main>'

**Comment by Gazler** [comment] 2016-01-08 08:43
@EverLin33 I think they may be a small misunderstanding here.

When I said `PATH_TO_FILE` I meant the path to the file that you downloaded. Could you please try again replacing `PATH_TO_FILE` with the location of the file you downloaded.

**Comment by EverLin33** [comment] 2016-01-08 09:11
shame of myself........

here's the output:
D:\Downloads\githug-data\git_hug>githug reset D:\Downloads\2e5410fd06d814a92516-
0e2703cf494157c3a3ac11852f2d0b606806f22a\checkout_tag.rb
********************************************************************************

*                                    Githug                                    *

********************************************************************************

resetting level

Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.


D:\Downloads\githug-data\git_hug>git checkout v1.2
Note: checking out 'v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c0b1e53... Some more changes

D:\Downloads\githug-data\git_hug>githug test D:\Downloads\2e5410fd06d814a92516-0
e2703cf494157c3a3ac11852f2d0b606806f22a\checkout_tag.rb --errors
********************************************************************************

*                                    Githug                                    *

********************************************************************************


Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.


5
"commit c0b1e532bf0dcb2cf94aa521019707557d021cbe\nAuthor: 鏋楅泟杈\x89 <xxx@xxx.com.cn>\nDate:   Fri Jan 8 17:09:03 2016 +0800\n\n    Some more changes
\n\ndiff --git a/app.rb b/app.rb\nindex 6bf6d7a..5141d92 100644\n--- a/app.rb\n+
++ b/app.rb\n@@ -1 +1,2 @@\n \"Some code\" \n+\"Buggy code\" \n"
(eval):35:in `block in setup': invalid byte sequence in GBK (ArgumentError)
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/lib/g
ithug/level.rb:105:in `test'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/lib/g
ithug/game.rb:41:in `test_level'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/lib/g
ithug/cli.rb:24:in `test'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or/task.rb:22:in `run'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or/invocation.rb:118:in `invoke_task'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or.rb:263:in `dispatch'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.14.6/lib/th
or/base.rb:389:in `start'
        from C:/Program Files/Ruby21/lib/ruby/gems/2.1.0/gems/githug-0.4.5/bin/g
ithug:4:in `<top (required)>'
        from C:/Program Files/Ruby21/bin/githug:23:in `load'
        from C:/Program Files/Ruby21/bin/githug:23:in `<main>'

**Comment by Gazler** [comment] 2016-01-08 09:18
Ok, one more thing to try:

```
set LC_ALL=en_US.UTF-8
set LANG=en_US.UTF-8
githug reset checkout_tag
git checkout v1.2
githug
```

**Comment by Gazler** [comment] 2016-01-08 09:23
The problem is the name used in your config contains a character that ruby doesn't like.

Could you please provide the exact value of `git config --get user.name` it looks to be "鏋楅泟杈" however I just want to be sure.

**Comment by EverLin33** [comment] 2016-01-08 10:04
"鏋楅泟杈" is actually my chinese name, and I ran githug in Windows cmd, not on Linux. So if the character is the problem, then I think it should not work an level 1 rather than 33. May be?...

**Comment by Gazler** [comment] 2016-01-08 10:19
In this specific case, it is using the output of a command that shows git commits. This command will also show your name, level 1 does not display your name.

Did you try those steps I suggested above?

**Comment by EverLin33** [comment] 2016-01-08 10:35
I tried, still doesn't work...

D:\Downloads\githug-data\git_hug>set LC_ALL=en_US.UTF-8

D:\Downloads\githug-data\git_hug>set LANG=en_US.UTF-8

D:\Downloads\githug-data\git_hug>githug reset checkout_tag
********************************************************************************

*                                    Githug                                    *

********************************************************************************

resetting level

Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.


D:\Downloads\githug-data\git_hug>git checkout v1.2
Note: checking out 'v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3e96308... Some more changes

D:\Downloads\githug-data\git_hug>githug
********************************************************************************

*                                    Githug                                    *

********************************************************************************

Sorry, this solution is not quite right!

Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.

**Comment by Gazler** [comment] 2016-01-08 10:55
Thanks for sticking with it. I have one more thing I would like you to try if you don't mind.

Download this level: https://gist.github.com/Gazler/2e5410fd06d814a92516 (I have updated it)

githug reset PATH_TO_FILE
git checkout v1.2
githug test PATH_TO_FILE --errors

**Comment by EverLin33** [comment] 2016-01-08 11:02
Actually, we are helping each other, so that is fine. ^_^

D:\Downloads\githug-data\git_hug>githug reset D:\Downloads\2e5410fd06d814a92516-
2b9cd869d24dbb3561db6ad7da338ffbf1fe2f9a\checkout_tag.rb
********************************************************************************

*                                    Githug                                    *

********************************************************************************

resetting level

Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.


D:\Downloads\githug-data\git_hug>git checkout v1.2
Note: checking out 'v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1a81ac6... Some more changes

D:\Downloads\githug-data\git_hug>githug test D:\Downloads\2e5410fd06d814a92516-2
b9cd869d24dbb3561db6ad7da338ffbf1fe2f9a\checkout_tag.rb --errors
********************************************************************************

*                                    Githug                                    *

********************************************************************************


Name: checkout_tag
Level: 33
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2`.


Valid solution

**Comment by Gazler** [comment] 2016-01-08 12:21
Thanks for testing. This appears to be working now. I'll push up a new version later today.

**Comment by Gazler** [comment] 2016-01-08 17:57
Fixed in 0.4.6

**Closed by Gazler** 2016-01-08 17:57 UTC

**Comment by EverLin33** [comment] 2016-01-11 00:57
Thanks @Gazler

**Comment by EverLin33** [comment] 2016-01-11 09:19
I have updated to 0.4.6, passed 33, but failed 34, maybe the same problem?

D:\Downloads\git_hug>githug reset
********************************************************************************

*                                    Githug                                    *

********************************************************************************

resetting level

Name: checkout_tag_over_branch
Level: 34
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2` (N
ote: There is also a branch named `v1.2`).


D:\Downloads\git_hug>git checkout tags/v1.2
Note: checking out 'tags/v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at deef2e3... Some more changes

D:\Downloads\git_hug>githug
********************************************************************************

*                                    Githug                                    *

********************************************************************************

Sorry, this solution is not quite right!

Name: checkout_tag_over_branch
Level: 34
Difficulty: **

You need to fix a bug in the version 1.2 of your app. Checkout the tag `v1.2` (N
ote: There is also a branch named `v1.2`).

**Comment by Gazler** [comment] 2016-01-11 18:08
Wow. It is the same issue, thanks for raising it.

I have fixed this on master. Before I do another release, would you be able to install the version locally with:

```
git clone git@github.com:gazler/githug.git
cd githug
rake build
gem install pkg\githug-0.4.6.gem
```

If you find any more issues then we can fix them then do a release with all the fixes present.

Thanks.

**Comment by EverLin33** [comment] 2016-01-12 01:46
I can't execute the rake command in my git bash...
Never mind, just wait for your new release.

Thanks.
